# Generated by Django 5.2.4 on 2025-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason_for_increase', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBudgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('estimation_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
