# Generated by Django 5.2.4 on 2025-08-20 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_creation_projectbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_creation_projectbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
