# Generated by Django 5.2.4 on 2025-09-12 10:49

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectestimation',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='initial_estimation_amount',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='additional_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='estimation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='purchase_order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Received', 'Received'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
