# Generated by Django 5.2.4 on 2025-09-01 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_projectestimation_created_by_and_more'),
        ('project_creation', '0003_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_project', to='project_creation.project'),
        ),
    ]
