# Generated by Django 5.2.4 on 2025-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_projectestimation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='other_payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='payment_type',
            field=models.CharField(choices=[('Manpower', 'Manpower'), ('Operation Cost', 'Operation Cost'), ('Transport', 'Transport'), ('Interest', 'Interest'), ('Other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
