# Generated by Django 5.2.4 on 2025-09-03 12:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_projectpaymenttracking_other_payment_type_and_more'),
        ('masterdata', '0001_initial'),
        ('project_creation', '0010_alter_project_project_name'),
        ('roles', '0002_add_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('budget_utilization', 'Budget Utilization (%)'), ('pending_percentage', 'Pending Percentage (%)'), ('completed_milestones', 'Completed Milestones Amount')], max_length=64)),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<=')], max_length=4)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='projectestimation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectpaymentmilestone',
            options={'ordering': ['due_date', 'id'], 'verbose_name': 'Payment Milestone', 'verbose_name_plural': 'Payment Milestones'},
        ),
        migrations.AlterModelOptions(
            name='projectpaymenttracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project Payment Tracking', 'verbose_name_plural': 'Project Payment Trackings'},
        ),
        migrations.RenameField(
            model_name='projectpaymenttracking',
            old_name='is_deleted',
            new_name='budget_exceeded_approved',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='approved_estimation',
        ),
        migrations.RemoveField(
            model_name='projectpaymentmilestone',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='projectpaymentmilestone',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='projectpaymenttracking',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='projectpaymenttracking',
            name='other_payment_type',
        ),
        migrations.RemoveField(
            model_name='projectpaymenttracking',
            name='pending',
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectpaymentmilestone',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpaymentmilestone',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpaymentmilestone',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=6),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='is_budget_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='retention_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='estimation_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_provided', to='roles.userrole'),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='estimation_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_reviewed', to='roles.userrole'),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='estimation_review_by_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_estimations', to='project_creation.client'),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations', to='project_creation.project'),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='purchase_order_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectpaymentmilestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='projectpaymentmilestone',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpaymentmilestone',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='additional_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='approved_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='hold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='masterdata.masterdata'),
        ),
        migrations.CreateModel(
            name='AdditionalBudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requests_created', to=settings.AUTH_USER_MODEL)),
                ('payment_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='budget.projectpaymenttracking')),
            ],
            options={
                'verbose_name': 'Additional Budget Request',
                'verbose_name_plural': 'Additional Budget Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=255)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=255)),
                ('prev_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='budget.projectpaymenttracking')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('payment_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.projectpaymenttracking')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
