# Generated by Django 5.2.4 on 2025-09-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_rule_alter_projectestimation_options_and_more'),
        ('project_creation', '0010_alter_project_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpaymenttracking',
            name='hold',
        ),
        migrations.RemoveField(
            model_name='projectpaymenttracking',
            name='hold_reason',
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='project_creation.project')),
            ],
        ),
    ]
