# Generated by Django 5.2.4 on 2025-09-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_remove_projectpaymenttracking_hold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='budget.projectpaymenttracking'),
        ),
    ]
