# Generated by Django 5.2.4 on 2025-09-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_hold_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hold',
            old_name='project',
            new_name='payment_tracking',
        ),
    ]
