# Generated by Django 5.2.4 on 2025-09-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_rename_project_hold_payment_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR')], default='INR', max_length=6),
        ),
    ]
