# Generated by Django 5.2.4 on 2025-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_projectpaymenttracking_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=6),
        ),
    ]
