# Generated by Django 5.2.4 on 2025-09-09 12:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_changerequest'),
        ('project_creation', '0010_alter_project_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='model_name',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='changed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='changed_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='data',
            new_name='extra',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='note',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_value',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BudgetPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('STRICT', 'Strict - block when exceeding approved estimation'), ('FLEXIBLE', 'Flexible - allow but warn/audit'), ('AUTO_ADJUST', 'Auto Adjust - trim to remaining budget')], default='STRICT', max_length=32)),
                ('warning_threshold_percent', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_policy', to='project_creation.project')),
            ],
        ),
    ]
