# Generated by Django 5.2.4 on 2025-09-11 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectestimation',
            options={'ordering': ['-version', '-created_at']},
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='created_from_cr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_estimations', to='budget.changerequest'),
        ),
    ]
