# Generated by Django 5.2.4 on 2025-09-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_alter_projectestimation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectestimation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='correlation_id',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='created_from_cr',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='estimation_provider',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='estimation_review',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='estimation_review_by_client',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='is_deleted',
        ),
    ]
