# Generated by Django 5.2.4 on 2025-09-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_alter_projectestimation_options_and_more'),
        ('project_creation', '0010_alter_project_project_name'),
        ('roles', '0002_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimation',
            name='estimation_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_provided', to='roles.userrole'),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='estimation_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_reviewed', to='roles.userrole'),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='estimation_review_by_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_estimations', to='project_creation.client'),
        ),
    ]
