# Generated by Django 5.2.4 on 2025-09-11 12:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_remove_projectestimation_approved_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimation',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Received', 'Received'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
