# Generated by Django 5.1.6 on 2025-08-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=255, unique=True)),
                ('module_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
