# Generated by Django 5.1.6 on 2025-08-12 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0002_add_new_permissions'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_resource', models.CharField(max_length=100)),
                ('type_of_resource', models.CharField(choices=[('Freelance', 'Freelance'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Consultant', 'Consultant'), ('Temporary', 'Temporary'), ('Vendor', 'Vendor'), ('Outsourced', 'Outsourced'), ('Apprentice', 'Apprentice')], max_length=50)),
                ('contact_details', models.CharField(blank=True, max_length=100, null=True)),
                ('pan', models.CharField(blank=True, max_length=15, null=True)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('work_type', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_set', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='users.module')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='roles_creation.role')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
