# Generated by Django 5.1.6 on 2025-08-12 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_masterdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdata',
            name='username',
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='name_of_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
