# Generated by Django 5.1.6 on 2025-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_masterdata_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdata',
            name='role',
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='work_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Shift-based', 'Shift-based'), ('Field Work', 'Field Work'), ('Project-based', 'Project-based'), ('On-call', 'On-call'), ('Travel-intensive', 'Travel-intensive'), ('Flexible Hours', 'Flexible Hours'), ('Training', 'Training')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
