# Generated by Django 5.1.6 on 2025-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_masterdata_role_alter_masterdata_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='type_of_resource',
            field=models.CharField(choices=[('Freelance', 'Freelance'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Consultant', 'Consultant'), ('Temporary', 'Temporary'), ('Vendor', 'Vendor'), ('Outsourced', 'Outsourced'), ('Apprentice', 'Apprentice'), ('Other', 'Other')], max_length=50),
        ),
    ]
