# Generated by Django 5.1.6 on 2025-08-12 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_masterdata_name_of_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='users.module'),
        ),
    ]
