# Generated by Django 5.1.6 on 2025-08-21 10:07

import django.db.models.deletion
import django.utils.timezone
import project_creation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0001_initial'),
        ('roles_creation', '0002_add_new_permissions'),
        ('users', '0008_alter_masterdata_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_name', models.CharField(max_length=255)),
                ('poc_name', models.CharField(max_length=255)),
                ('poc_email', models.EmailField(max_length=254)),
                ('poc_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.CreateModel(
            # name='Document',
            # fields=[
            #     # ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            #     # ('file', models.FileField(upload_to='uploads/', validators=[project_creation.models.validate_file])),
            #     ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            #     ('object_id', models.PositiveIntegerField()),
            #     ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            # ],
        # ),
        migrations.CreateModel(
            name='PaymentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hold_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.masterdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('payment_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='project_creation.paymenttracking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('status', models.CharField(choices=[('Development', 'Development'), ('Testing', 'Testing'), ('UAT', 'UAT'), ('Production', 'Production'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Development', max_length=50)),
                ('project_type', models.CharField(choices=[('Internal', 'Internal'), ('Client-Based', 'Client-Based')], default='Internal', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_accountant', to='roles_creation.userrole')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_creation.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_modified_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_organization', to='organization.organisation')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='roles_creation.userrole')),
            ],
        ),
        migrations.AddField(
            model_name='paymenttracking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project_creation.project'),
        ),
        migrations.CreateModel(
            name='PaymentStatusTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=50)),
                ('approved_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('milestone_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('milestone_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('milestone_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hold_reason', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_payments', to='project_creation.project')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='project_creation.paymenttracking')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='project_creation.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('estimation_date', models.DateField()),
                ('estimation_provider', models.CharField(max_length=255)),
                ('estimation_review', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_estimation_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimation_review_by_client', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_estimation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_order_status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='project_creation.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=50)),
                ('estimation_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason_for_increase', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='project_creation.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
