# Generated by Django 5.2.4 on 2025-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpoc',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
