# Generated by Django 5.2.4 on 2025-09-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.DeleteModel(
            name='IDPattern',
        ),
    ]
