# Generated by Django 5.1.6 on 2025-08-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0002_alter_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='project',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='related_payment',
        ),
        migrations.RemoveField(
            model_name='paymentmilestone',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentmilestone',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='paymentmilestone',
            name='payment_tracking',
        ),
        migrations.RemoveField(
            model_name='paymentstatustracking',
            name='project',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='project',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='project',
        ),
        migrations.DeleteModel(
            name='Estimation',
        ),
        migrations.DeleteModel(
            name='FinanceTransaction',
        ),
        migrations.DeleteModel(
            name='PaymentMilestone',
        ),
        migrations.DeleteModel(
            name='PaymentStatusTracking',
        ),
        migrations.DeleteModel(
            name='PaymentTracking',
        ),
        migrations.DeleteModel(
            name='ProjectBudget',
        ),
    ]
