# Generated by Django 5.2.4 on 2025-09-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0003_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=100),
        ),
    ]
