# Generated by Django 5.2.4 on 2025-08-20 07:39

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0003_clientpoc_created_at_clientpoc_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpoc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True,default=timezone.now
),
        ),
        migrations.AlterField(
            model_name='clientpoc',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True,default=timezone.now),
        ),
    ]
