# Generated by Django 5.1.6 on 2025-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0003_remove_financetransaction_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Development', 'Development'), ('Testing', 'Testing'), ('UAT', 'UAT'), ('Production', 'Production'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Planning', max_length=50),
        ),
    ]
