# Generated by Django 5.2.4 on 2025-08-20 07:40

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0004_alter_clientpoc_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpoc',
            name='created_at',
            

        ),
        migrations.RemoveField(
            model_name='clientpoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientpoc',
            name='modified_at',
            
        ),
        migrations.RemoveField(
            model_name='clientpoc',
            name='modified_by',
        ),
    ]
