# Generated by Django 5.1.6 on 2025-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
