# Generated by Django 5.2.4 on 2025-08-20 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0005_remove_clientpoc_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpoc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now
),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientpoc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientpoc',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
        ),
        migrations.AddField(
            model_name='clientpoc',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
