# Generated by Django 5.2.4 on 2025-08-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0006_clientpoc_created_at_clientpoc_created_by_and_more'),
        ('roles', '0002_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Client',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientpoc',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='estimation_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_provider', to='roles.userrole'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='estimation_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_reviewer', to='roles.userrole'),
        ),
    ]
