# Generated by Django 5.2.4 on 2025-08-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0007_client_client_alter_clientpoc_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Client',
            new_name='Client_company',
        ),
    ]
