# Generated by Django 5.2.4 on 2025-09-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0007_alter_project_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
    ]
