# Generated by Django 5.2.4 on 2025-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0008_remove_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
