# Generated by Django 5.2.4 on 2025-08-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0008_rename_client_client_client_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='estimation_review_by_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_reviewer', to='project_creation.client'),
        ),
    ]
