# Generated by Django 5.2.4 on 2025-08-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_creation', '0009_alter_estimation_estimation_review_by_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='estimation_provider',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='estimation_review',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='estimation_review_by_client',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='project',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='related_payment',
        ),
        migrations.RemoveField(
            model_name='paymentmilestone',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentmilestone',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='paymentmilestone',
            name='payment_tracking',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='project',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Estimation',
        ),
        migrations.DeleteModel(
            name='FinanceTransaction',
        ),
        migrations.DeleteModel(
            name='PaymentMilestone',
        ),
        migrations.DeleteModel(
            name='PaymentTracking',
        ),
    ]
