# Generated by Django 5.2.4 on 2025-08-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_projectbudget_resource_document_content_type_and_more'),
        ('project_creation', '0010_remove_estimation_created_by_and_more'),
        ('user_profile', '0002_category_remove_resource_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceAssignment',
        ),
    ]
