# Generated by Django 5.1.6 on 2025-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creation', '0002_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('In review', 'In Review'), ('On Hold', 'On Hold'), ('done', 'Done')], default='todo', max_length=50),
        ),
    ]
