# Generated by Django 5.1.6 on 2025-09-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creation', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('in_review', 'In Review'), ('on_hold', 'On Hold'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
